# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'explain.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ExplainForm(object):
    def __init__(self, form) -> None:
        self.setupUi(form)

    def setupUi(self, ExplainForm):
        ExplainForm.setObjectName("ExplainForm")
        ExplainForm.resize(700, 700)
        self.BackPushButton = QtWidgets.QPushButton(ExplainForm)
        self.BackPushButton.setGeometry(QtCore.QRect(600, 660, 89, 25))
        self.BackPushButton.setObjectName("BackPushButton")
        self.ExplainTableWidget = QtWidgets.QTableWidget(ExplainForm)
        self.ExplainTableWidget.setGeometry(QtCore.QRect(20, 70, 661, 571))
        self.ExplainTableWidget.setObjectName("ExplainTableWidget")
        self.ExplainTableWidget.setColumnCount(0)
        self.ExplainTableWidget.setRowCount(0)
        self.PaintModelLabel = QtWidgets.QLabel(ExplainForm)
        self.PaintModelLabel.setGeometry(QtCore.QRect(260, 20, 161, 31))
        self.PaintModelLabel.setObjectName("PaintModelLabel")

        self.retranslateUi(ExplainForm)
        QtCore.QMetaObject.connectSlotsByName(ExplainForm)

    def retranslateUi(self, ExplainForm):
        _translate = QtCore.QCoreApplication.translate
        ExplainForm.setWindowTitle(_translate("ExplainForm", "Form"))
        self.BackPushButton.setText(_translate("ExplainForm", "Назад"))
        self.PaintModelLabel.setText(_translate("ExplainForm", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Name of model</span></p></body></html>"))